name: CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Add Tag name'
        required: true
        default: '@login'
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner will use the latest Ubuntu image

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK using Eclipse Temurin
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Specify the Java version you need
        distribution: 'temurin'  # Use 'temurin' (Eclipse Temurin, previously AdoptOpenJDK)
        java-package: jdk
        architecture: x64

    # Step 3: Grant execute permissions to gradlew (in case it's missing)
    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew  # Ensure gradlew has execute permissions

    # Step 4: Run Gradle build
    - name: Run Gradle build
      run: ./gradlew clean test -D"tag=${{ github.event.inputs.tag }}
