name: CI

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner will use the latest Ubuntu image

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (you can specify the version you need)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can use a different Java version if required
        distribution: 'adoptopenjdk'

    # Step 3: Install Gradle
    - name: Install Gradle
      uses: gradle/wrapper-validation-action@v1

    # Step 4: Run the tests using Gradle
    - name: Run tests with Gradle
      run: ./gradlew clean test  # Running Gradle clean and test tasks

    # Step 5: Upload the test results (Optional: If you want to see the test results)
    # - name: Upload Cucumber reports
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: cucumber-reports
    #     path: target/cucumber-reports/  # Path where reports are generated
